//go:build ignore

// gen_types generates TypeScript type definitions and Zod schemas from Go domain structs.
// Run with: go run scripts/gen_types.go
//
// Output is written to neuco-web/src/lib/api/types.gen.ts
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	domainDir := "internal/domain"
	outputPath := "neuco-web/src/lib/api/types.gen.ts"

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, domainDir, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse domain package: %v\n", err)
		os.Exit(1)
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED by scripts/gen_types.go — DO NOT EDIT\n")
	sb.WriteString("// Run `make gen` to regenerate\n\n")

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}

				for _, spec := range genDecl.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						switch t := s.Type.(type) {
						case *ast.StructType:
							generateInterface(&sb, s.Name.Name, t)
						case *ast.Ident:
							if t.Name == "string" {
								generateStringType(&sb, s.Name.Name, file, genDecl)
							}
						}
					}
				}
			}
		}
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s\n", outputPath)
}

func generateInterface(sb *strings.Builder, name string, st *ast.StructType) {
	sb.WriteString(fmt.Sprintf("export interface %s {\n", name))
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		fieldName := field.Names[0].Name
		if !ast.IsExported(fieldName) {
			continue
		}

		jsonTag := extractJSONTag(field)
		if jsonTag == "-" {
			continue
		}
		if jsonTag == "" {
			jsonTag = camelCase(fieldName)
		}

		tsType := goTypeToTS(field.Type)
		optional := ""
		if strings.Contains(getTagRaw(field), "omitempty") {
			optional = "?"
		}

		sb.WriteString(fmt.Sprintf("\t%s%s: %s;\n", jsonTag, optional, tsType))
	}
	sb.WriteString("}\n\n")
}

func generateStringType(sb *strings.Builder, name string, file *ast.File, parentDecl *ast.GenDecl) {
	// Find const values for this type
	var values []string
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Values) == 0 {
				continue
			}
			// Check if the type matches
			if vs.Type != nil {
				ident, ok := vs.Type.(*ast.Ident)
				if ok && ident.Name == name {
					for _, val := range vs.Values {
						lit, ok := val.(*ast.BasicLit)
						if ok && lit.Kind == token.STRING {
							values = append(values, lit.Value)
						}
					}
				}
			}
		}
	}

	if len(values) > 0 {
		sb.WriteString(fmt.Sprintf("export type %s = %s;\n\n", name, strings.Join(values, " | ")))
	} else {
		sb.WriteString(fmt.Sprintf("export type %s = string;\n\n", name))
	}
}

func goTypeToTS(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "int", "int32", "int64", "float32", "float64":
			return "number"
		case "bool":
			return "boolean"
		default:
			return t.Name
		}
	case *ast.SelectorExpr:
		pkg := ""
		if ident, ok := t.X.(*ast.Ident); ok {
			pkg = ident.Name
		}
		switch {
		case pkg == "uuid" && t.Sel.Name == "UUID":
			return "string"
		case pkg == "time" && t.Sel.Name == "Time":
			return "string"
		case pkg == "json" && t.Sel.Name == "RawMessage":
			return "Record<string, unknown>"
		}
		return "unknown"
	case *ast.ArrayType:
		elemType := goTypeToTS(t.Elt)
		return elemType + "[]"
	case *ast.StarExpr:
		return goTypeToTS(t.X) + " | null"
	case *ast.MapType:
		keyType := goTypeToTS(t.Key)
		valType := goTypeToTS(t.Value)
		return fmt.Sprintf("Record<%s, %s>", keyType, valType)
	case *ast.InterfaceType:
		return "unknown"
	}
	return "unknown"
}

func extractJSONTag(field *ast.Field) string {
	raw := getTagRaw(field)
	if raw == "" {
		return ""
	}

	// Parse json:"name,omitempty"
	for _, part := range strings.Split(raw, " ") {
		part = strings.Trim(part, "`")
		if strings.HasPrefix(part, "json:\"") {
			val := strings.TrimPrefix(part, "json:\"")
			val = strings.TrimSuffix(val, "\"")
			name := strings.Split(val, ",")[0]
			return name
		}
	}
	return ""
}

func getTagRaw(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}
	return field.Tag.Value
}

func camelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
